"""
Archive fashion brands and keywords for filtering.
Expanded list covering Japanese archive, European designers, and streetwear.
"""

# Primary archive brands to search for
ARCHIVE_BRANDS = [
    # === JAPANESE ARCHIVE ===
    "number (n)ine",
    "number nine",
    "undercover",
    "hysteric glamour",
    "comme des garcons",
    "cdg",
    "comme des garcons homme plus",
    "comme des garcons black",
    "comme des garcons tao",
    "comme des garcons junya man",
    "comme des garcons parfum",
    "cdg x supreme",
    "yohji yamamoto",
    "y's",
    "yohji yamamoto pour homme",
    "yohji yamamoto costume d'homme",
    "issey miyake",
    "pleats please",
    "homme plisse",
    "issey miyake men",
    "issey miyake plantation",
    "kapital",
    "visvim",
    "wtaps",
    "neighborhood",
    "bape",
    "a bathing ape",
    "human made",
    "nigo",
    "takahiromiyashita thesoloist",
    "soloist",
    "julius",
    "julius_7",
    "if six was nine",
    "l.g.b.",
    "lgb",
    "undercoverism",
    "undercover x supreme",
    "jun takahashi",
    "fragment design",
    "sacai",
    "sacai x nike",
    "junya watanabe",
    "ganryu",
    "kolor",
    "white mountaineering",
    "needles",
    "engineered garments",
    "beams",
    "united arrows",
    "beauty & youth",
    "wacko maria",
    "cav empt",
    "c.e",
    "kansai yamamoto",
    "rei kawakubo",
    "kiko kostadinov",
    
    # === EUROPEAN ARCHIVE ===
    "rick owens",
    "drkshdw",
    "rick owens mainline",
    "rick owens runway leather",
    "rick owens dunks",
    "raf simons",
    "raf simons redux",
    "raf simons sterling ruby",
    "raf simons x fred perry",
    "maison margiela",
    "martin margiela",
    "margiela",
    "mmm",
    "maison martin margiela",
    "maison margiela artisanal",
    "margiela artisanal line 0",
    "helmut lang",
    "helmut lang jeans",
    "helmut lang painter denim",
    "helmut lang astro jacket",
    "helmut lang flak jacket",
    "helmut lang bulletproof vest",
    "ann demeulemeester",
    "ann demeulemeester homme",
    "dries van noten",
    "haider ackermann",
    "carol christian poell",
    "ccp",
    "ccp prosthetic",
    "boris bidjan saberi",
    "bbs",
    "ma+",
    "maurizio amadei",
    "guidi",
    "a1923",
    "layer-0",
    "incarnation",
    "ie",
    "isaac sellam",
    "lost & found",
    "m.a+",
    "paul harnden",
    "geoffrey b small",
    "elena dawson",
    "walter van beirendonck",
    "craig green",
    "jil sander",
    "label under construction",
    "hussein chalayan",
    "chalayan",
    
    # === STREETWEAR / HYPE ===
    "supreme",
    "palace",
    "stussy",
    "the hundreds",
    "kith",
    "off-white",
    "off white",
    "virgil abloh",
    "vetements",
    "demna gvasalia",
    "balenciaga",
    "gosha rubchinskiy",
    "alyx",
    "1017 alyx 9sm",
    "heron preston",
    "ambush",
    "yoon ahn",
    "awge",
    "bianca chandon",
    "noah",
    "online ceramics",
    "brain dead",
    "denim tears",
    "tremaine emory",
    
    # === LUXURY / DESIGNER ===
    "hermes",
    "hermès",
    "chanel",
    "karl lagerfeld chanel",
    "prada",
    "prada uomo",
    "miu miu",
    "gucci",
    "tom ford gucci",
    "tom ford yves saint laurent",
    "bottega veneta",
    "celine",
    "old celine",
    "celine phoebe philo",
    "phoebe philo celine",
    "celine homme",
    "saint laurent",
    "saint laurent paris",
    "saint laurent rive gauche",
    "slp",
    "hedi slimane",
    "hedi slimane dior homme",
    "hedi slimane saint laurent",
    "dior homme",
    "dior homme aw04",
    "dior homme aw06",
    "dior homme aw07",
    "dior",
    "louis vuitton",
    "louis vuitton marc jacobs",
    "lv",
    "givenchy",
    "givenchy riccardo tisci",
    "givenchy alexander mcqueen",
    "burberry",
    "burberry prorsum",
    "alexander mcqueen",
    "mcqueen",
    "alexander wang",
    "vivienne westwood",
    "vivienne westwood gold label",
    "vivienne westwood red label",
    "vivienne westwood anglomania",
    "seditionaries",
    "malcolm mclaren vivienne westwood",
    "jean paul gaultier",
    "jpg",
    "jpg soleil",
    "jpg cyber",
    "jpg archive denim",
    "gaultier",
    "thierry mugler",
    "mugler",
    "versace",
    "gianni versace",
    "dolce gabbana",
    "d&g",
    "roberto cavalli",
    "prada sport",
    "prada linea rossa",
    "acne studios",
    "our legacy",
    "lemaire",
    "the row",
    "khaite",
    "toteme",
    "ami paris",
    "balmain",
    "balmain decarnin",
    "nicolas ghesquiere balenciaga",
    "demna balenciaga",
    "fendi",
    "karl lagerfeld fendi",
    "fendi kim jones",
    "valentino",
    "valentino garavani",
    "valentino couture",
    "schiaparelli",
    "lanvin",
    "lanvin alber elbaz",
    "lanvin homme",
    "alaia",
    "maison alaia",
    "alaia homme",
    "paco rabanne",
    "courreges",
    "kenzo",
    "marni",
    "moschino",
    "yves saint laurent",
    
    # === AMERICAN / OTHER ===
    "enfants riches deprimes",
    "erd",
    "chrome hearts",
    "kapital",
    "gallery dept",
    "amiri",
    "mike amiri",
    "john elliott",
    "robert geller",
    "greg lauren",
    "r13",
    "simon miller",
    "y/project",
    "martine rose",
    "wales bonner",
    "grace wales bonner",
    "casablanca",
    "jacquemus",
    "marine serre",
    "ottolinger",
    
    # === FOOTWEAR SPECIFIC ===
    "rick owens ramones",
    "rick owens geobasket",
    "maison margiela tabi",
    "balenciaga triple s",
    "balenciaga track",
    "salomon xt-6",
    "salomon xt-4",
    
    # === DENIM SPECIFIC ===
    "evisu",
    "samurai jeans",
    "iron heart",
    "pure blue japan",
    "pbj",
    "momotaro",
    "oni denim",
    "sugar cane",
    "warehouse",
    "tcb jeans",
    "resolute",
    "full count",
    "dry bones",
]

# Keywords that indicate archive/vintage pieces
ARCHIVE_KEYWORDS = [
    "archive",
    "vintage",
    "rare",
    "grail",
    "ss98", "aw98", "ss99", "aw99",
    "ss00", "aw00", "ss01", "aw01",
    "ss02", "aw02", "ss03", "aw03",
    "ss04", "aw04", "ss05", "aw05",
    "ss06", "aw06", "ss07", "aw07",
    "ss08", "aw08", "ss09", "aw09",
    "ss10", "aw10", "ss11", "aw11",
    "ss12", "aw12", "ss13", "aw13",
    "fw",
    "runway",
    "sample",
    "japan",
    "made in japan",
    "made in italy",
    "deadstock",
    "nwt",
    "bnwt",
]

# Categories to search
CATEGORIES = [
    "jacket",
    "blazer",
    "coat",
    "pants",
    "trousers",
    "jeans",
    "denim",
    "shirt",
    "hoodie",
    "sweater",
    "knit",
    "t-shirt",
    "tee",
    "boots",
    "shoes",
    "sneakers",
    "bag",
    "accessories",
]


def normalize_brand(brand: str) -> str:
    """Normalize brand name for matching."""
    return brand.lower().strip().replace("-", " ").replace("_", " ")


def get_search_queries() -> list[str]:
    """Generate search queries combining brands with optional keywords."""
    queries = []
    for brand in ARCHIVE_BRANDS:
        queries.append(brand)
    return queries


# Priority brands for faster scraping (most valuable/common)
PRIORITY_BRANDS = [
    # High value archive - European
    "raf simons",
    "rick owens",
    "helmut lang",
    "maison margiela",
    "ann demeulemeester",
    "dries van noten",
    "carol christian poell",
    "boris bidjan saberi",
    "haider ackermann",
    
    # Japanese archive
    "number nine",
    "undercover",
    "comme des garcons",
    "yohji yamamoto",
    "issey miyake",
    "junya watanabe",
    "sacai",
    "visvim",
    "julius",
    
    # Luxury houses
    "dior homme",
    "saint laurent",
    "celine",
    "gucci",
    "prada",
    "hermes",
    "chanel",
    "louis vuitton",
    "bottega veneta",
    "balenciaga",
    "givenchy",
    "fendi",
    "valentino",
    
    # Designer archive
    "jean paul gaultier",
    "thierry mugler",
    "vivienne westwood",
    "alexander mcqueen",
    "hussein chalayan",
    
    # Streetwear
    "supreme",
    "vetements",
    "chrome hearts",
    "off-white",
    
    # Japanese streetwear
    "hysteric glamour",
    "kapital",
    "wtaps",
    "neighborhood",
    "bape",
    "human made",
    "cav empt",
    "wacko maria",
    
    # Other high value
    "enfants riches deprimes",
    "gallery dept",
    "amiri",
]
